######################################################################
#
# File name : tb_layer_1_simulate.do
# Created on: Sat Feb 25 13:35:13 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L blk_mem_gen_v8_4_2 -L unisims_ver -L unimacro_ver -L secureip -lib xil_defaultlib xil_defaultlib.tb_layer_1 xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {tb_layer_1_wave.do}

view wave
view structure
view signals

do {tb_layer_1.udo}

run 1000ns
