######################################################################
#
# File name : tb_layer_1_compile.do
# Created on: Sat Feb 25 13:35:11 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib modelsim_lib/work
vlib modelsim_lib/msim

vlib modelsim_lib/msim/xil_defaultlib
vlib modelsim_lib/msim/blk_mem_gen_v8_4_2

vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib
vmap blk_mem_gen_v8_4_2 modelsim_lib/msim/blk_mem_gen_v8_4_2

vlog -64 -incr -sv -work xil_defaultlib  \
"D:/vivado/Vivado/2018.3/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \

vlog -64 -incr -work xil_defaultlib  \
"../../../../conv_prj.srcs/sources_1/ip/mult_16/mult_16_sim_netlist.v" \
"../../../../conv_prj.srcs/sources_1/ip/shift_ram_conv_5_5/shift_ram_conv_5_5_sim_netlist.v" \

vlog -64 -incr -work blk_mem_gen_v8_4_2  \
"../../../../conv_prj.ip_user_files/ipstatic/simulation/blk_mem_gen_v8_4.v" \

vlog -64 -incr -work xil_defaultlib  \
"../../../../conv_prj.srcs/sources_1/ip/rom_16x784/sim/rom_16x784.v" \
"../../../../conv_prj.srcs/sources_1/new/conv.v" \
"../../../../conv_prj.srcs/sources_1/new/layer_1.v" \
"../../../../conv_prj.srcs/sources_1/new/pic_input.v" \
"../../../../conv_prj.srcs/sim_1/new/tb_layer_1.v" \

# compile glbl module
vlog -work xil_defaultlib "glbl.v"

quit -force

