######################################################################
#
# File name : tb_layer_1_wave.do
# Created on: Sat Feb 25 13:28:12 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
