# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/86158/Desktop/CONV_/conv_prj.srcs/sources_1/ip/shift_ram_conv_5_5/shift_ram_conv_5_5.xci
# IP: The module: 'shift_ram_conv_5_5' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/86158/Desktop/CONV_/conv_prj.srcs/sources_1/ip/shift_ram_conv_5_5/shift_ram_conv_5_5_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'shift_ram_conv_5_5'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/86158/Desktop/CONV_/conv_prj.srcs/sources_1/ip/shift_ram_conv_5_5/shift_ram_conv_5_5.xci
# IP: The module: 'shift_ram_conv_5_5' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/86158/Desktop/CONV_/conv_prj.srcs/sources_1/ip/shift_ram_conv_5_5/shift_ram_conv_5_5_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'shift_ram_conv_5_5'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
