# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/86158/Desktop/CONV_/conv_prj.srcs/sources_1/ip/mult_16/mult_16.xci
# IP: The module: 'mult_16' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/86158/Desktop/CONV_/conv_prj.srcs/sources_1/ip/mult_16/mult_16_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mult_16'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/86158/Desktop/CONV_/conv_prj.srcs/sources_1/ip/mult_16/mult_16.xci
# IP: The module: 'mult_16' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/86158/Desktop/CONV_/conv_prj.srcs/sources_1/ip/mult_16/mult_16_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mult_16'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
